### ISSUE TITLE
Good job man, although it closes unfortunately

### ISSUE THREAD

**Issue by Cli98** [jinfagang/CenterNet_Pro_Max#12]
Good job @jinfagang 

BTW I find a recent implementation for effdet. Try this repo, https://github.com/rwightman/efficientdet-pytorch/blob/master/train.py

Good luck to you,

**Comment by lucasjinreal** [comment]
@Cli98  centernet will have issue on detecting large objects. thanks for your sharing on this project, did u tried this one? Does it easy to reproduce on custom dataset?
