### ISSUE TITLE
能否简单介绍下如何准备数据集以及指定GPU编号

### ISSUE THREAD

**Issue by cxzhou95** [jinfagang/CenterNet_Pro_Max#4]
简单看了一下想训练coco试试，但是在代码里没找到定位数据集path的地方。。。以及怎么指定使用第几个GPU训练，如果单机多卡训练的话应该改哪些设置，谢谢!

**Comment by lucasjinreal** [comment]
我们这几天会更新自定义数据集训练内容

**Comment by lucasjinreal** [comment]
I have updated custom dataset training (coco like).

**Comment by xiazi-yu** [comment]
@cxzhou95 单机多卡训练你会设置了么
