### ISSUE TITLE
How to train on multi gpu device?

### ISSUE THREAD

**Issue by zhangjinsong3** [jinfagang/CenterNet_Pro_Max#6]
Thanks for your amazing work! I have tried to train the code on my own dataset with multi gpus, but it still works on the first one! And I find that the parameter '--num-gpus' not be used! How did you train on 8 gpus?

**Comment by LigZhong** [comment]
@zhangjinsong3 hello, how did you solve this?

**Comment by zhangjinsong3** [comment]
@LigZhong I did not solve this, but I found centernet-better can train on multi gpus. Thus I use CenterNet-better instead.
